### ISSUE TITLE
How to do inverse transform after scaling dataset using MinMaxScale?

### ISSUE THREAD

**Issue by adrian2x** [repetere/modelscript#1]

**Comment by yawetse** [comment]
Hi @adrian2x that hasn't been implemented yet. I'd be happy to accept any pull requests with that feature though!

**Comment by yawetse** [comment]
Hi @adrian2x inverse transforms have been added.

there are two new util functions:

```
StandardScalerTransforms // returns two functions that can standard scale new inputs and reverse scale new outputs
MinMaxScalerTransforms // returns two functions that can standard scale new inputs and reverse scale new outputs
```

when you pass in an array, both functions will return the scaling and inverse scaling function (As well as the data scaled
